# Config file for automatic testing at travis-ci.org
# and providing coverage reporting at coveralls.io

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install: 
    - pip install -r requirements.txt
    - pip install coveralls
script:
    py.test --cov scrapyd_api tests/
after_success:
  coveralls
